### ISSUE TITLE
Menu Item "Start automatically ..." promises dialog, but none is shown

### ISSUE THREAD

**Issue by Achimh3011** [matthiasbertsch/atlassian-notifier#1]
A menu item with three dots usually incurs further interaction with the user. This is not the case here (and shouldn't) so the three dots should go.

**Comment by Achimh3011** [comment]
Cool idea otherwise!

**Comment by matthiasbertsch** [comment]
Thanks! A fix for this is released with [v1.0.1](https://github.com/matthiasbertsch/atlassian-notifier/releases/tag/v1.0.1).
